import Head from "next/head";
import styles from "../styles/Home.module.css";
import Link from "next/link";
import { Button, Typography, styled } from "@mui/material";

const StyledText = styled(Typography)({
  textIndent: "10px",
});

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Typography variant="h4">Intro:</Typography>
        <StyledText variant="body1" mb={2}>
          Consectetur nostrud proident culpa sit et sit veniam sunt laboris esse
          id. Aute do ad excepteur reprehenderit. Id id pariatur excepteur velit
          laborum adipisicing in cupidatat Lorem ut ad esse. Excepteur do
          nostrud non do amet in consequat. Eu nulla commodo quis excepteur
          occaecat et non ex tempor Lorem velit. Ad ipsum duis aute fugiat
          consequat aliqua magna non consequat. Duis non ipsum do id esse. Dolor
          ullamco consectetur laboris consequat excepteur consectetur ex ipsum
          aute laborum eu exercitation. Est voluptate enim sint tempor laborum
          ullamco deserunt eiusmod esse est irure. Et proident veniam non
          incididunt proident mollit et nulla qui. Laborum quis proident aute
          laboris incididunt nisi eiusmod do occaecat sunt velit cupidatat. Sint
          fugiat aliquip labore dolore aliquip aliqua culpa ullamco
          exercitation. Elit consectetur et amet adipisicing veniam do eiusmod
          eu magna quis nostrud. Veniam proident adipisicing non id aute Lorem
          commodo incididunt qui. Ex veniam quis nulla ullamco culpa veniam
          consequat aute. Culpa eiusmod veniam irure occaecat elit. Laboris
          pariatur nostrud consectetur sit excepteur non ipsum mollit ad anim
          sit velit. Eiusmod consequat do deserunt magna aliquip mollit
          reprehenderit reprehenderit eiusmod.
        </StyledText>
        <StyledText variant="body2" mb={2}>
          Ea reprehenderit ea proident Lorem voluptate velit. Est veniam
          deserunt esse irure veniam sit culpa et aute sint. Ut anim anim qui
          amet ut reprehenderit mollit nostrud officia fugiat in. In occaecat
          nostrud mollit sit et reprehenderit aliquip occaecat enim commodo.
          Occaecat et aute esse incididunt eiusmod reprehenderit consectetur
          aliquip minim. Fugiat occaecat non commodo incididunt ipsum. Velit
          enim ullamco veniam aute anim deserunt anim consectetur magna velit.
          Nostrud velit amet excepteur officia nulla labore laboris. Mollit
          tempor nostrud qui deserunt nostrud dolore culpa ut ex duis. Aute
          aliqua cupidatat proident quis. Est minim consequat labore nostrud est
          minim id consequat esse cillum irure Lorem ea ullamco. Veniam elit sit
          labore amet sunt elit ut incididunt. Cupidatat sunt aliquip mollit
          magna tempor exercitation quis culpa aliqua. Est minim proident nulla
          laboris dolore in cupidatat consectetur aliquip dolor exercitation.
        </StyledText>
      </div>
   <div style={{ display: 'flex',justifyContent:'space-between',alignItems:'center' }}>
   <Link href="/nested/contacts" >
        <Button variant="contained" color="secondary" sx={{ marginBottom: '5px' }}>
          Go to contact page
        </Button>
      </Link>
   <Link href="/nested" >
        <Button variant="contained" color="success" sx={{ marginBottom: '5px' }}>
          Go to userlist page
        </Button>
      </Link>
   </div>
    </div>
  );
}
